name: hs-bittorrent
version: 0.1.0.0
license: BSD3

dependencies:
  - base >= 4.7 && < 5
  - HTTP
  - network-simple 
  - bytestring 
  - text
  - time 
  - cryptohash
  - base16-bytestring
  - entropy
  - directory
  - filepath
  - binary
  - async
  - stm

executables:
  hs-bittorrent-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
